# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250326-034416-critical-rest

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexEntityExtractor
    case_sensitive: false
    use_word_boundaries: true
    patterns:
      # Pattern cho số lượng (top 3, hạng nhất...)
      - pattern: "\\b(top|hạng|số)\\s?([1-5]|nhất|hai|ba|bốn|năm)\\b"
        entity: "quantity"
        value: "$2" # Lấy group thứ 2

      # Pattern riêng cho các số thứ tự
      - pattern: "\\b(nhất|đầu|số\\s?1|thứ\\s?1)\\b"
        entity: "quantity"
        value: "1"
      - pattern: "\\b(hai|nhì|số\\s?2|thứ\\s?2)\\b"
        entity: "quantity"
        value: "2"
      - pattern: "\\b(ba|số\\s?3|thứ\\s?3)\\b"
        entity: "quantity"
        value: "3"

      # Pattern cho thời gian (HH:MM)
      - pattern: "\\b((0?[0-9]|1[0-9]|2[0-3]):([0-5][0-9])\\b"
        entity: "startTime"
      - pattern: "\\b((0?[0-9]|1[0-9]|2[0-3]):([0-5][0-9])\\b"
        entity: "endTime"

      # Pattern cho ngày tháng
      - pattern: "\\b(hôm nay|chiều nay|tối nay|sáng nay|nay)\\b"
        entity: "quantityDate"
        value: "0"
      - pattern: "\\b(ngày mai|mai|sáng mai|chiều mai|tối mai)\\b"
        entity: "quantityDate"
        value: "1"
      - pattern: "\\b(ngày kia|hôm kia|2 ngày (nữa|sau))\\b"
        entity: "quantityDate"
        value: "2"
      - pattern: "\\b(3 ngày (nữa|sau))\\b"
        entity: "quantityDate"
        value: "3"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/

policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
