# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250326-034416-critical-rest

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: WhitespaceTokenizer

  - name: RegexEntityExtractor
    case_sensitive: false
    use_word_boundaries: true
    patterns:
      # Bắt số thứ hạng top CLB
      - pattern: "\\b(top|hạng|số|thứ)?\\s?(1|2|3|4|5|nhất|hai|ba|bốn|năm)\\b"
        entity: "quantity"
        value: "$2"

      # Bắt thời gian bắt đầu
      - pattern: "\\b(từ|bắt đầu lúc)?\\s*((0?[0-9]|1[0-9]|2[0-3]):([0-5][0-9]))\\b"
        entity: "startTime"
        value: "$2"

      # Bắt thời gian kết thúc
      - pattern: "\\b(đến|tới|kết thúc lúc)?\\s*((0?[0-9]|1[0-9]|2[0-3]):([0-5][0-9]))\\b"
        entity: "endTime"
        value: "$2"

      # Bắt ngày
      - pattern: "\\b(hôm nay|chiều nay|tối nay|sáng nay|nay)\\b"
        entity: "quantityDate"
        value: "0"
      - pattern: "\\b(ngày mai|mai|sáng mai|chiều mai|tối mai)\\b"
        entity: "quantityDate"
        value: "1"
      - pattern: "\\b(ngày kia|hôm kia|2 ngày (nữa|sau))\\b"
        entity: "quantityDate"
        value: "2"
      - pattern: "\\b(3 ngày (nữa|sau))\\b"
        entity: "quantityDate"
        value: "3"

  - name: RegexFeaturizer

  - name: LexicalSyntacticFeaturizer

  - name: CountVectorsFeaturizer

  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.2

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.6
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    # core_fallback_threshold: 0.4
    # core_fallback_action_name: "action_default_fallback"
    # enable_fallback_prediction: True
  # - name: TEDPolicy
  #   max_history: 5
  #   epochs: 100
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
